on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: self-hosted
#    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.1
    - uses: NuGet/setup-nuget@v1.0.2
    - run: nuget restore WebApplication1/WebApplication1.sln
    - run: msbuild WebApplication1/WebApplication3/WebApplication3.csproj /property:Configuration=Release /p:DeployOnBuild=true
    - uses: microsoft/variable-substitution@v1 
      with:
        files: '${{ github.workspace }}/WebApplication1/WebApplication3/Web.config'
      env:
        configuration.appSettings.foo: "b"
    - run: | 
        & "C:/Program Files (x86)/IIS/Microsoft Web Deploy V3/msdeploy.exe" -verb:sync -source:contentPath="$env:github_workspace/WebApplication1/WebApplication3/obj/Release/Package/PackageTmp" -dest:contentPath="site"
